/*
Sql Data Viewer, Copyright Tim Abell 2015
All rights reserved.

A tool for browsing the data in any rdbms databse
through a series of generated html pages.

Provides navigation between tables via the foreign keys
defined in the database's schema.
*/

package main

import (
	"database/sql"
	"fmt"
	_ "github.com/mattn/go-sqlite3"
	"net/http"
	"os"
)

var db string

func main() {
	db = os.Args[1]
	fmt.Println("Sql Data Viewer; Copyright 2015 Tim Abell <tim@timwise.co.uk>")
	fmt.Printf("Connecting to db: %s\n", db)
	http.HandleFunc("/", handler)
	fmt.Println("Listening on http://localhost:8080/")
	fmt.Println("Press Ctrl-C to kill server")
	http.ListenAndServe(":8080", nil)
}

func handler(resp http.ResponseWriter, req *http.Request) {
	fmt.Fprintln(resp, htmlHeader)
	dbc, err := sql.Open("sqlite3", db)
	if err != nil {
		fmt.Println("connection error", err)
		return
	}
	defer dbc.Close()
	fmt.Fprintf(resp, "<p id='connected'>Connected to <span class='config-value'>%s</span></p>\n", db)
	tables, err := getTables(dbc)
	if err != nil {
		fmt.Println("error getting table list", err)
		return
	}
	for _, table := range tables {
		showTable(resp, dbc, table)
	}
	fmt.Fprintln(resp, htmlFooter)
}

func showTable(resp http.ResponseWriter, dbc *sql.DB, table string) {
	rows, err := dbc.Query("select * from " + table)
	if err != nil {
		fmt.Println("select error", err)
		return
	}
	defer rows.Close()
	fmt.Fprintf(resp, "<h2>Table %s</h2>\n", table)
	fmt.Fprintln(resp, `<table border=1>`)
	cols, err := rows.Columns()
	if err != nil {
		fmt.Println("error getting column names", err)
		return
	}
	fmt.Fprintln(resp, "<tr>")
	for _, col := range cols {
		fmt.Fprintf(resp, "<th>%s</th>\n", col)
	}
	fmt.Fprintln(resp, "</tr>")
	// http://stackoverflow.com/a/23507765/10245 - getting ad-hoc column data
	rowData := make([]interface{}, len(cols))
	rowDataPointers := make([]interface{}, len(cols))
	for i := 0; i < len(cols); i++ {
		rowDataPointers[i] = &rowData[i]
	}
	for rows.Next() {
		err := rows.Scan(rowDataPointers...)
		if err != nil {
			fmt.Println("error reading row data", err)
			return
		}
		fmt.Fprintln(resp, "\t<tr>")
		for colIndex := range cols {
			colData := rowData[colIndex]
			fmt.Fprint(resp, "\t\t<td>")
			switch colData.(type) {
			case int64:
				fmt.Fprintf(resp, "%d", colData)
			case nil:
				fmt.Fprint(resp, "<span class='null'>[null]</span>")
			default:
				fmt.Fprintf(resp, "%s", colData)
			}
			fmt.Fprintln(resp, "</td>")
		}
		fmt.Fprintln(resp, "\t</tr>")
	}
	fmt.Fprintln(resp, "</table>")
	fks(resp, dbc, table)
}

func fks(resp http.ResponseWriter, dbc *sql.DB, table string) {
	rows, err := dbc.Query("PRAGMA foreign_key_list('" + table + "');")
	if err != nil {
		fmt.Println("select error", err)
		return
	}
	defer rows.Close()
	fmt.Fprintln(resp, "<ul>")
	for rows.Next() {
		var id, seq int
		var parentTable, from, to, onUpdate, onDelete string
		rows.Scan(&id, &seq, &parentTable, &from, &to, &onUpdate, &onDelete)
		fmt.Fprintf(resp, "\t<li>key: %s references %s.%s</li>\n", from, parentTable, to)
	}
	fmt.Fprintln(resp, "</ul>")
}

func getTables(dbc *sql.DB) (tables []string, err error) {
	rows, err := dbc.Query("SELECT name FROM sqlite_master WHERE type='table';")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var name string
		rows.Scan(&name)
		tables = append(tables, name)
	}
	return tables, nil
}

const htmlHeader = `<!DOCTYPE html>
<html lang='en'>
<head>
	<title>Sql Data Viewer</title>
	<style type='text/css'>
		body { background-color: #f9fff9; margin: 1em; }
		.null { color: #999; }
		#connected { font-style: italic; }
		.config-value { background-color: #eee; }
		footer { color: #666; text-align: right; font-size: smaller; }
		footer a { color: #66c; }
	</style>
</head>
<body>
<h1>Sql Data Viewer</h1>`

const htmlFooter = `<footer>
	Generated by Sql Data Viewer<br/>
	Sql Data Viewer &copy; 2015 <a href='mailto:tim@timwise.co.uk?subject=Sql Data Viewer'>Tim Abell</a>
</footer>
</body>
</html>`
